# Generated by Django 5.1.2 on 2024-10-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('processor', models.CharField(max_length=50, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=50, verbose_name='Оперативная память')),
                ('motherboard', models.CharField(max_length=50, verbose_name='Материнская плата')),
                ('drives', models.TextField(verbose_name='Накопители')),
                ('power_supply', models.CharField(max_length=50, verbose_name='Блок питания')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeripheralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('physical_place', models.TextField(verbose_name='Физическое расположение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('mfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mfp', verbose_name='МФУ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('purpose', models.TextField(default='', verbose_name='Назначение')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeteoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post', verbose_name='Должность')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание запроса')),
                ('status', models.IntegerField(choices=[(0, 'Создан'), (1, 'В работе'), (2, 'Выполнен')], verbose_name='Статус запроса')),
                ('created_at', models.DateTimeField(null=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(null=True, verbose_name='Выполнен')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место')),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('peripheral_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.peripheraltype', verbose_name='Тип переферии')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mfp',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Название')),
                ('inventory_number', models.CharField(default='', max_length=100, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(default='', max_length=100, verbose_name='Серийный номер')),
                ('technical_condition', models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], verbose_name='Техническое состояние')),
                ('disabling_reason', models.TextField(default='', verbose_name='Причина снятия')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.computerconfiguration', verbose_name='Конфигурация (сборка)')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
