# Generated by Django 5.1.2 on 2024-10-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('motherboard', models.CharField(max_length=50)),
                ('drives', models.TextField()),
                ('power_supply', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeripheralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('physical_place', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure')),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure')),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeteoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.structure')),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.mfp')),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worksite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite')),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('peripheral_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.peripheraltype')),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mfp',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite'),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.computerconfiguration')),
                ('technial_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.technicalcondition')),
                ('worksite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.worksite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
