# Generated by Django 5.1.2 on 2024-10-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'В работе'), (2, 'Выполнен')], default=0, verbose_name='Статус запроса'),
        ),
        migrations.AlterField(
            model_name='server',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='server',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='inventory_number',
            field=models.CharField(default='', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='serial_number',
            field=models.CharField(default='', max_length=50, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят'), (3, 'Ремонт')], default=0, verbose_name='Техническое состояние'),
        ),
    ]
