# Generated by Django 5.1.2 on 2024-10-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartridge',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='meteounit',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='mfp',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='networkequipment',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='peripheral',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.RenameField(
            model_name='ups',
            old_name='technial_condition',
            new_name='technical_condition',
        ),
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='meteounit',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mfp',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='monitor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ups',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='computerconfiguration',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='peripheraltype',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='server',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='technicalcondition',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ups',
            name='inventory_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ups',
            name='serial_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
