# Generated by Django 5.1.2 on 2024-10-16 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_computer_inventory_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='mfp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.mfp', verbose_name='МФУ'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='server',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='disabling_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина снятия'),
        ),
    ]
