# Generated by Django 5.1.2 on 2024-10-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_cartridge_disabling_reason_alter_cartridge_mfp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfp',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
    ]
