# Generated by Django 5.1.2 on 2024-10-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_computer_worksite_alter_meteounit_structure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджы'},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='computerconfiguration',
            options={'verbose_name': 'Конфигурация (сборка) компьютера', 'verbose_name_plural': 'Конфигурации (сборки) компьютеров'},
        ),
        migrations.AlterModelOptions(
            name='meteounit',
            options={'verbose_name': 'Прибор (гидро / метео / агро)', 'verbose_name_plural': 'Приборы (гидро / метео / агро)'},
        ),
        migrations.AlterModelOptions(
            name='mfp',
            options={'verbose_name': 'МФУ', 'verbose_name_plural': 'МФУ'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': 'Монитор', 'verbose_name_plural': 'Мониторы'},
        ),
        migrations.AlterModelOptions(
            name='networkequipment',
            options={'verbose_name': 'Сетевое оборудование', 'verbose_name_plural': 'Сетевое оборудование'},
        ),
        migrations.AlterModelOptions(
            name='peripheral',
            options={'verbose_name': 'Периферия', 'verbose_name_plural': 'Периферия'},
        ),
        migrations.AlterModelOptions(
            name='peripheraltype',
            options={'verbose_name': 'Тип периферии', 'verbose_name_plural': 'Типы периферии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': 'Сервер', 'verbose_name_plural': 'Сервера'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Структура', 'verbose_name_plural': 'Структуры'},
        ),
        migrations.AlterModelOptions(
            name='ups',
            options={'verbose_name': 'ИБП', 'verbose_name_plural': 'ИБП'},
        ),
        migrations.AlterModelOptions(
            name='worksite',
            options={'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='peripheral_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.peripheraltype', verbose_name='Тип периферии'),
        ),
    ]
