# Generated by Django 5.1.2 on 2024-10-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_cartridge_options_alter_computer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'ordering': ['name', 'technical_condition'], 'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджы'},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['name', 'technical_condition', 'worksite'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='computerconfiguration',
            options={'ordering': ['name'], 'verbose_name': 'Конфигурация (сборка) компьютера', 'verbose_name_plural': 'Конфигурации (сборки) компьютеров'},
        ),
        migrations.AlterModelOptions(
            name='meteounit',
            options={'ordering': ['name', 'technical_condition', 'structure'], 'verbose_name': 'Прибор (гидро / метео / агро)', 'verbose_name_plural': 'Приборы (гидро / метео / агро)'},
        ),
        migrations.AlterModelOptions(
            name='mfp',
            options={'ordering': ['name', 'technical_condition', 'worksite'], 'verbose_name': 'МФУ', 'verbose_name_plural': 'МФУ'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'ordering': ['name', 'technical_condition', 'worksite'], 'verbose_name': 'Монитор', 'verbose_name_plural': 'Мониторы'},
        ),
        migrations.AlterModelOptions(
            name='networkequipment',
            options={'ordering': ['name', 'technical_condition', 'structure'], 'verbose_name': 'Сетевое оборудование', 'verbose_name_plural': 'Сетевое оборудование'},
        ),
        migrations.AlterModelOptions(
            name='peripheral',
            options={'ordering': ['name', 'peripheral_type'], 'verbose_name': 'Периферия', 'verbose_name_plural': 'Периферия'},
        ),
        migrations.AlterModelOptions(
            name='peripheraltype',
            options={'ordering': ['name'], 'verbose_name': 'Тип периферии', 'verbose_name_plural': 'Типы периферии'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name', 'structure'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['status', 'created_at', 'completed_at'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name', 'technical_condition', 'structure'], 'verbose_name': 'Сервер', 'verbose_name_plural': 'Сервера'},
        ),
        migrations.AlterModelOptions(
            name='ups',
            options={'ordering': ['name', 'technical_condition', 'worksite'], 'verbose_name': 'ИБП', 'verbose_name_plural': 'ИБП'},
        ),
        migrations.AlterModelOptions(
            name='worksite',
            options={'ordering': ['name', 'post'], 'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
    ]
