# Generated by Django 5.1.2 on 2024-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_cartridge_options_alter_computer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='number',
            field=models.CharField(default='', max_length=50, verbose_name='Номер картриджа'),
        ),
    ]
