# Generated by Django 5.1.2 on 2024-10-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_cartridge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='ip_address',
            field=models.CharField(max_length=15, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='meteounit',
            name='verification_date',
            field=models.DateField(null=True, verbose_name='Дата поверки'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='ip_address',
            field=models.CharField(max_length=15, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='server',
            name='ip_address',
            field=models.CharField(max_length=15, null=True, verbose_name='IP адрес'),
        ),
    ]
