# Generated by Django 5.1.2 on 2024-10-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_computer_ip_address_meteounit_verification_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['name', 'technical_condition', 'worksite', 'ip_address'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='networkequipment',
            options={'ordering': ['name', 'technical_condition', 'structure', 'ip_address'], 'verbose_name': 'Сетевое оборудование', 'verbose_name_plural': 'Сетевое оборудование'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['name', 'technical_condition', 'structure', 'ip_address'], 'verbose_name': 'Сервер', 'verbose_name_plural': 'Сервера'},
        ),
        migrations.AddField(
            model_name='computer',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Комменарий'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IP адрес'),
        ),
    ]
