# Generated by Django 5.1.2 on 2024-10-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_computer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='refills',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заправок'),
        ),
    ]
