# Generated by Django 5.1.2 on 2024-10-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_cartridge_refills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'ordering': ['name', 'technical_condition', 'refills'], 'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджы'},
        ),
    ]
