# Generated by Django 5.1.2 on 2024-10-18 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_cartridge_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='mfp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.mfp', unique=True, verbose_name='МФУ'),
        ),
    ]
