# Generated by Django 5.1.2 on 2024-10-21 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_cartridge_mfp_alter_computer_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='Номер картриджа'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Комменарий'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='post',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='request',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='server',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.post', verbose_name='Должность'),
        ),
    ]
