# Generated by Django 5.1.2 on 2024-10-23 05:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_computer_worksite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='mfp',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='installed_mfp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.mfp', verbose_name='МФУ'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='current_cartridge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.cartridge', verbose_name='Картридж'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.computerconfiguration', verbose_name='Конфигурация (сборка)'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', unique=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='verification_date',
            field=models.DateField(blank=True, help_text='Дата и время в формате DD.MM.YYYY hh:mm:ss', null=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', unique=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='peripheral_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.peripheraltype', verbose_name='Тип периферии'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='post',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='request',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время в формате DD.MM.YYYY hh:mm:ss', null=True, verbose_name='Выполнен'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Дата и время в формате DD.MM.YYYY hh:mm:ss', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='request',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', unique=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='server',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='worksite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.post', verbose_name='Должность'),
        ),
    ]
