# Generated by Django 5.1.2 on 2024-10-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_rename_installed_mfp_cartridge_current_mfp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Номер картриджа'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='verification_date',
            field=models.DateField(blank=True, help_text='Дата в формате DD.MM.YYYY', null=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='request',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='server',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='server',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='inventory_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='technical_condition',
            field=models.IntegerField(choices=[(0, 'Готов к установке'), (1, 'В работе'), (2, 'Снят (нерабочий)'), (3, 'В ремонте')], default=0, verbose_name='Техническое состояние'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.worksite', verbose_name='Рабочее место'),
        ),
    ]
