# Generated by Django 5.1.2 on 2024-10-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_cartridge_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Отдел / подразделение', 'verbose_name_plural': 'Отделы / подразеления'},
        ),
        migrations.AddField(
            model_name='structure',
            name='abbreviative',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='ФИО'),
        ),
    ]
