# Generated by Django 5.1.2 on 2024-10-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_structure_options_structure_abbreviative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='abbreviative',
        ),
        migrations.AddField(
            model_name='structure',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Отдел / подразделение'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Отдел / подразделение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Отдел / подразделение'),
        ),
        migrations.AlterField(
            model_name='server',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.structure', verbose_name='Отдел / подразделение'),
        ),
    ]
