# Generated by Django 5.1.2 on 2024-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_meteounit_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='abbreviative',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Сокращение'),
        ),
    ]
