# Generated by Django 5.1.2 on 2024-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_remove_structure_abbreviative_structure_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='short_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Сокращение'),
        ),
    ]
