# Generated by Django 5.1.2 on 2024-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_structure_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='server',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='server',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Серийный номер'),
        ),
    ]
