# Generated by Django 5.1.2 on 2024-10-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_computer_inventory_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', unique=True, verbose_name='IP адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', unique=True, verbose_name='IP адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4', unique=True, verbose_name='IP адрес'),
            preserve_default=False,
        ),
    ]
