# Generated by Django 5.1.2 on 2024-10-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_alter_computer_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('device_id', models.PositiveIntegerField()),
                ('service_date', models.DateField(auto_now_add=True, help_text='Дата обслуживания', verbose_name='Дата поверки')),
                ('description', models.TextField(help_text='Описание обслуживания', verbose_name='Описание')),
            ],
        ),
        migrations.AddField(
            model_name='cartridge',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='computer',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='meteounit',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='server',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='ups',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип устройства'),
        ),
    ]
