# Generated by Django 5.1.2 on 2024-10-31 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_servicehistory_cartridge_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='meteounit',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='mfp',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='networkequipment',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='peripheral',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='ups',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время в формате DD.MM.YYYY hh:mm:ss', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='service_date',
            field=models.DateField(auto_now_add=True, help_text='Дата обслуживания', verbose_name='Дата обслуживания'),
        ),
    ]
