# Generated by Django 5.1.2 on 2024-10-31 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_devicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='computer',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='meteounit',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='server',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
        migrations.AddField(
            model_name='ups',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.devicetype', verbose_name='Тип устройства'),
        ),
    ]
