# Generated by Django 5.1.2 on 2024-11-13 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_alter_servicehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджи'},
        ),
        migrations.RemoveField(
            model_name='servicehistory',
            name='service_date',
        ),
        migrations.AddField(
            model_name='cartridge',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='computer',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='meteounit',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='mfp',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='networkequipment',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='peripheral',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='server',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='service_date_end',
            field=models.DateField(help_text='Конец обслуживания', null=True, verbose_name='Конец обслуживания'),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='service_date_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Начало обслуживания', verbose_name='Начало обслуживания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ups',
            name='last_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
    ]
