# Generated by Django 5.1.2 on 2024-11-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_alter_cartridge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='meteounit',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='mfp',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='networkequipment',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='peripheral',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
        migrations.AlterField(
            model_name='servicehistory',
            name='service_date_end',
            field=models.DateField(blank=True, help_text='Конец обслуживания', null=True, verbose_name='Конец обслуживания'),
        ),
        migrations.AlterField(
            model_name='ups',
            name='last_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.servicehistory'),
        ),
    ]
