# Generated by Django 5.1.2 on 2024-11-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_remove_servicehistory_service_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'verbose_name': 'Картридж', 'verbose_name_plural': 'Картриджи'},
        ),
    ]
